// <auto-generated />
using DemoProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20260325011053_Name")]
    partial class Name
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("DemoProject.Models.ExampleParent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("example_parent");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Temp"
                        });
                });

            modelBuilder.Entity("DemoProject.Models.ExampleTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ParentID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("example_table");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ParentID = -1
                        },
                        new
                        {
                            ID = -2,
                            ParentID = -1
                        },
                        new
                        {
                            ID = -3,
                            ParentID = -1
                        });
                });

            modelBuilder.Entity("DemoProject.Models.ExampleTable", b =>
                {
                    b.HasOne("DemoProject.Models.ExampleParent", "ExampleParent")
                        .WithMany("ExampleTables")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_$ExampleTable_ExampleParent");

                    b.Navigation("ExampleParent");
                });

            modelBuilder.Entity("DemoProject.Models.ExampleParent", b =>
                {
                    b.Navigation("ExampleTables");
                });
#pragma warning restore 612, 618
        }
    }
}
