// <auto-generated />
using DemoProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(CarsContext))]
    [Migration("20260327015019_SeedDataOdometer")]
    partial class SeedDataOdometer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DemoProject.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Mitsubishi"
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("model");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ManufacturerId = -1,
                            Name = "Supra"
                        },
                        new
                        {
                            Id = -2,
                            ManufacturerId = -1,
                            Name = "Soarer"
                        },
                        new
                        {
                            Id = -3,
                            ManufacturerId = -2,
                            Name = "3000GT"
                        },
                        new
                        {
                            Id = -4,
                            ManufacturerId = -2,
                            Name = "Eclipse"
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Vehicle", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("TEXT")
                        .HasColumnName("vin");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<int>("Odometer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("odometer");

                    b.HasKey("Vin");

                    b.HasIndex("ModelId");

                    b.ToTable("vehicle");

                    b.HasData(
                        new
                        {
                            Vin = "VIN00000000000001",
                            ModelId = -1,
                            Odometer = 100
                        },
                        new
                        {
                            Vin = "VIN00000000000002",
                            ModelId = -2,
                            Odometer = 100
                        },
                        new
                        {
                            Vin = "VIN00000000000003",
                            ModelId = -3,
                            Odometer = 100
                        },
                        new
                        {
                            Vin = "VIN00000000000004",
                            ModelId = -4,
                            Odometer = 100
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.HasOne("DemoProject.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DemoProject.Models.Vehicle", b =>
                {
                    b.HasOne("DemoProject.Models.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("DemoProject.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
