// <auto-generated />
using DemoProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20260318010925_FixPK")]
    partial class FixPK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DemoProject.Models.EfmigrationsLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("__EFMigrationsLock");
                });

            modelBuilder.Entity("DemoProject.Models.ExampleParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("example_parent");
                });

            modelBuilder.Entity("DemoProject.Models.ExampleTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ParentId" }, "IX_example_table_parent_id");

                    b.ToTable("example_table");
                });

            modelBuilder.Entity("DemoProject.Models.ExampleTable", b =>
                {
                    b.HasOne("DemoProject.Models.ExampleParent", "Parent")
                        .WithMany("ExampleTables")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DemoProject.Models.ExampleParent", b =>
                {
                    b.Navigation("ExampleTables");
                });
#pragma warning restore 612, 618
        }
    }
}
