// <auto-generated />
using DemoProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20260320011756_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("DemoProject.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Toyota"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Mitsubishi"
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("model");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ManufacturerID = -1,
                            Name = "Supra"
                        },
                        new
                        {
                            ID = -2,
                            ManufacturerID = -1,
                            Name = "Soarer"
                        },
                        new
                        {
                            ID = -3,
                            ManufacturerID = -2,
                            Name = "3000GT"
                        },
                        new
                        {
                            ID = -4,
                            ManufacturerID = -2,
                            Name = "Eclipse"
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("TEXT")
                        .HasColumnName("vin");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("colour");

                    b.Property<int>("ModelID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_year");

                    b.HasKey("VIN");

                    b.HasIndex("ModelID");

                    b.ToTable("vehicle");

                    b.HasData(
                        new
                        {
                            VIN = "VIN00000000000001",
                            Colour = "Red",
                            ModelID = -1,
                            ModelYear = 1998
                        },
                        new
                        {
                            VIN = "VIN00000000000002",
                            Colour = "Black",
                            ModelID = -2,
                            ModelYear = 1995
                        },
                        new
                        {
                            VIN = "VIN00000000000003",
                            Colour = "White",
                            ModelID = -3,
                            ModelYear = 1999
                        },
                        new
                        {
                            VIN = "VIN00000000000004",
                            Colour = "Blue",
                            ModelID = -4,
                            ModelYear = 2001
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.HasOne("DemoProject.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_$Model_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DemoProject.Models.Vehicle", b =>
                {
                    b.HasOne("DemoProject.Models.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_$Vehicle_Model");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("DemoProject.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
