// <auto-generated />
using DemoProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20260313012105_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("DemoProject.Models.ClassRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_number");

                    b.HasKey("ID");

                    b.ToTable("example_parent");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            RoomNumber = 101
                        },
                        new
                        {
                            ID = -2,
                            RoomNumber = 102
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClassRoomID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("ID");

                    b.HasIndex("ClassRoomID");

                    b.ToTable("example_table");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ClassRoomID = -1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = -2,
                            ClassRoomID = -1,
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = -3,
                            ClassRoomID = -1,
                            FirstName = "Test",
                            LastName = "Student"
                        },
                        new
                        {
                            ID = -4,
                            ClassRoomID = -2,
                            FirstName = "A",
                            LastName = "Student"
                        },
                        new
                        {
                            ID = -5,
                            ClassRoomID = -2,
                            FirstName = "B",
                            LastName = "Student"
                        },
                        new
                        {
                            ID = -6,
                            ClassRoomID = -2,
                            FirstName = "C",
                            LastName = "Student"
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Student", b =>
                {
                    b.HasOne("DemoProject.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_$Student_ClassRoom");

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("DemoProject.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
