// <auto-generated />
using DemoProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20260320011457_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("DemoProject.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("model");
                });

            modelBuilder.Entity("DemoProject.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("TEXT")
                        .HasColumnName("vin");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("colour");

                    b.Property<int>("ModelID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_year");

                    b.HasKey("VIN");

                    b.HasIndex("ModelID");

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.HasOne("DemoProject.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_$Model_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DemoProject.Models.Vehicle", b =>
                {
                    b.HasOne("DemoProject.Models.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_$Vehicle_Model");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("DemoProject.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DemoProject.Models.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
